In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor, ExtraTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import math
import xgboost as xgb

In [74]:
data = pd.read_csv('Alldata.csv')
data

,State,variant,share_max,share_first,max_date,first_date,CDC_Region,max_var_cases_per_week,first_var_cases_week,Alpha,...,B.1.1.529,B.1.1.7,B.1.526,B.1.617.2,BA.1.1,BA.2,BA.2.12.1,BA.4,BA.4.6,BA.5
0,Alabama,B.1.1.529,0.255104,0.007616,1/22/22,12/4/21,4,29658.174650,23.342629,0,...,1,0,0,0,0,0,0,0,0,0
1,Alabama,B.1.1.7,0.475491,0.006229,3/20/21,1/16/21,4,3741.161449,144.776091,1,...,0,1,0,0,0,0,0,0,0,0
2,Alabama,B.1.526,0.075334,0.003289,3/20/21,1/16/21,4,592.724962,76.444344,0,...,0,0,1,0,0,0,0,0,0,0
3,Alabama,B.1.617.2,0.984046,0.006657,9/4/21,4/24/21,4,32504.999020,25.657797,0,...,0,0,0,1,0,0,0,0,0,0
4,Alabama,BA.1.1,0.735191,0.006385,1/22/22,12/4/21,4,85472.534430,19.569541,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,Wyoming,BA.2,0.132220,0.001821,6/18/22,1/15/22,8,297.890653,12.038433,0,...,0,0,0,0,0,1,0,0,0,0
506,Wyoming,BA.2.12.1,0.458981,0.110347,6/18/22,4/9/22,8,1034.083873,12.579566,0,...,0,0,0,0,0,0,1,0,0,0
507,Wyoming,BA.4,0.115121,0.034549,7/16/22,5/28/22,8,203.418187,15.615933,0,...,0,0,0,0,0,0,0,1,0,0
508,Wyoming,BA.4.6,0.055114,0.016557,8/20/22,7/2/22,8,55.885658,18.477122,0,...,0,0,0,0,0,0,0,0,1,0
509,Wyoming,BA.5,0.757610,0.045357,7/16/22,5/28/22,8,1338.696068,20.501199,0,...,0,0,0,0,0,0,0,0,0,1

In [76]:
x = data.loc[:, data.columns != 'diff_weeks']
y = (data['diff_weeks'])

x = x.iloc[: , -39:]
x

0       7
1       9
2       9
3      19
4       7
       ..
505    22
506    10
507     7
508     7
509     7
Name: diff_weeks, Length: 510, dtype: int64

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [49]:
train = xgb.DMatrix(x_train, label=y_train)
test = xgb.DMatrix(x_test, label=y_test)

param = {
    'max_depth': 4,
    'eta': 0.3,
    'num_class': 1}

epochs = 10

In [50]:
model = xgb.train(param, train, epochs)

In [71]:
predict = model.predict(test)
print(predict)

print(metrics.mean_absolute_error(y_test, predict))
print(metrics.r2_score(y_test, predict))
print(metrics.mean_squared_error(y_test, predict))

mape = np.mean(np.abs((y_test - predict) / y_test))
print(mape)

[ 8.020736  22.016485  15.09079   12.633732  12.675334  17.891191
 12.8531685 15.180316   7.140942  10.760811  15.669355  12.514091
 16.370216   7.8893056  6.1546135 10.427413  16.64538   12.514844
  5.5954666  9.660316   6.5850773 11.15218   18.311615  24.988214
 10.817693  16.608803   8.759138  16.608803   7.0669684  5.979129
 12.633732  11.727545   8.554861  10.377148  11.955697  28.29184
 12.381499   7.1983986 13.928402  12.765162  12.192466  22.915443
 10.8566265 15.09079    6.5131392 10.889634  11.095731   9.932414
  6.8147364 15.847331   8.554861  11.596417  14.841503  16.2331
 16.019045  16.17937   10.939506  22.983768  10.210287   7.8893056
 14.893135   8.020736   9.5025215  9.654475  17.95938    7.8893056
 14.376192  12.192466   6.5131392 10.021832  10.859262  16.328453
 10.62938   15.669355   8.503196   5.5954666 13.928402  16.019045
 10.021832  27.855722  11.294821  16.226183  26.583601  13.158051
  7.6370735 11.351703  29.907877  23.327581  27.855722  15.1802225
 15.372022   7.0669684 11.600382   8.020736  11.133261  12.984599
  8.020736  10.749598  16.998518  16.804932  10.30814    5.5954666]
2.6100990258011163
0.7560958775690871
12.914188775412773
0.31215777911309667

In [72]:
predict = model.predict(train)
print(predict)

print(metrics.mean_absolute_error(y_train, predict))
print(metrics.mean_squared_error(y_train, predict))
print(metrics.r2_score(y_train, predict))

math.sqrt(9.32349912576549)

[10.887111  10.43403   10.62938   16.322285  14.746974   7.732409
 10.472963   8.554861  11.095731  12.192466   7.732409  22.983768
 15.09079   17.067959  11.130478  12.514091  13.02662   14.878405
 31.517687  11.022967  13.153766  20.51211   12.984599   6.8147364
  5.5954666 16.483664  12.739241  22.773125  19.069246  15.09079
 10.341402  15.537925   9.619931  31.659822  16.271278   7.1983986
 14.746974  11.955697  17.157839  12.543903  10.760811  15.09079
 10.686262   5.8476987 16.608803   8.101519   7.0669684  5.5954666
  8.020736  31.898275  15.048792  11.980081   7.8799195 19.069246
  7.732409  10.021832  14.026373  12.675334  22.678663  10.83701
  6.5131392 20.79316   32.086937  14.250233  10.30814   19.524511
 12.381499  10.62938   17.733242  14.113261  24.988214   6.5850773
 11.808803   5.5954666  9.659797  11.596417   6.8147364 34.10993
 15.13679   11.84865   11.596417   8.020736  27.855722   5.5954666
 15.09079    8.020736  32.870594  12.192466  13.650243  14.189008
 11.808803   6.8147364  9.915615  12.215951  10.377148  16.899548
 12.192466  14.113261  11.84865   12.192466  13.928402  10.59395
 30.65326   11.021065  16.402708  10.769434   6.1546135  7.5531387
 11.7888365  8.503196  15.847331  12.291671   9.919337  12.514091
 16.382442  14.320438   7.1983986 15.09079    7.6722107  9.933343
  9.919337  12.061035   8.886859  11.980081  19.069246   6.5850773
  6.760562   7.3619156  7.012794  19.937286  14.955675  11.497887
 14.878405   6.8147364  9.195575  10.210287  11.030078   5.5954666
  8.020736   8.127168  10.916587   8.886859  12.192466  14.320438
  8.554861   8.020736  14.108053  10.377148  12.765162   6.760562
 15.5950985  8.020736   9.304463  16.019045  10.43403   33.32627
 15.200915  15.64909   25.497072  12.514091  20.408772  35.670673
 10.421627  14.113261  31.86403    8.459728  30.733782  23.120466
 11.030078   7.6722107  9.952152  11.345646  12.313511  11.7411175
 16.482243  10.478484  10.021832  11.030078  16.241234  11.564088
  8.020736  11.345646  18.817669  23.327581  19.069246  10.994433
 25.032526  11.130478   7.732409   6.8147364 18.053219  11.133261
 25.497072  12.726476  33.45812   10.341402   9.902525   9.919337
  7.8893056  9.933343  22.678663   5.5954666  6.8147364 11.020749
 12.347066   7.0669684 22.613413  10.983884   8.503196   6.5131392
 13.981831  10.377148  26.740532   8.886859  11.600382   7.3619156
 12.338048   6.893016  10.83701    9.919337  27.855722  10.939506
 14.893135  10.314598   5.979129  13.776944   8.896195  17.157839
 17.067959  15.039749  17.66589   31.86403   10.725065  16.241234
 10.760811  10.725065  12.061035  11.349749  17.82795   27.724293
  9.384202   9.385297  12.514844   8.755428   7.1983986 34.10993
 11.919951   9.384202   8.554861  16.402708  12.945665  10.307468
  5.8476987 11.345646  11.864556  11.294821  15.921783  10.62938
 10.303     11.67337    7.0669684 12.543903  16.608803   5.5954666
  7.0669684 12.765162  16.455341  18.093002   8.020736  22.884007
 10.898647  11.351703  13.928402   8.020736  12.075684  34.10993
 17.32666    8.101519   7.0669684 12.514091  12.453494  16.51395
 24.988214  10.341402   8.020736  11.00183   17.199389  23.109827
 11.138607   8.020736   7.6370735 16.799158  10.307468  10.341402
 12.765162  16.615093  15.992094  10.377148  17.571415   9.475797
 11.133261  10.341402  11.214215  12.2482195 31.766426   8.020736
  7.1983986 12.192466  14.320438   8.50013    8.055873  10.405496
  8.020736  34.10993    5.8476987 10.377148  10.686262  29.561287
 12.765162  19.244781   8.020736  15.09079   10.274065   8.886859
 18.897678  13.686147  10.760811  10.512811  16.065804  14.320438
 10.749598  11.596417  16.170486  14.026373  15.392608  14.113261
 18.209309  30.65326   28.17024   11.96432   12.765162  31.492535
  8.020736  17.663958  15.309744   8.554861  15.992094  17.61279
  6.8147364 30.65326   10.936295   7.012794  11.351703   9.250289
  8.087901   8.503196  16.432995  12.381499  22.904554  12.525957
 20.161983  16.482243  16.615093  11.133261  12.803804  16.23143
 23.115198  27.855722  24.988214  12.2482195 14.189008  16.799158
  8.886859  15.799738   8.020736  16.281155   7.0669684 17.891191
 10.274065  20.945642  16.370216  16.328453  23.327581  32.086937
  7.1983986 11.84865   19.840014  11.955697  30.33499    6.5850773
 11.349749  10.889634  10.646415   5.8476987  8.33348   10.405496
  8.340134   8.503196  12.726476  27.724293  12.338048  17.157839
 11.596417  35.670673  10.405496   7.7794333 17.28123   13.716017 ]
2.1163623379726038
9.32349912576549
0.8582423768037202

3.0534405390911887